### ISSUE TITLE
The reader mode feature (for threads) don't works anymore

### ISSUE THREAD

**Issue by dobby1970** [BandarHL/BHTwitter#49] opened 2022-08-21 07:51 UTC
On the latest version off bh Twitter and Twitter itself, this feature is not working anymore! It's already a long time that it's not working I think 2-3 versions ago it stopped working!

**Comment by AuroraWright** [comment] 2022-08-22 01:53
Duplicate of https://github.com/BandarHL/BHTwitter/issues/32

**Closed** 2024-09-06 22:01 UTC
