### ISSUE TITLE
Option to revert the rebrand

### ISSUE THREAD

**Issue by twitter7** [BandarHL/BHTwitter#183] opened 2023-09-17 01:16 UTC
Would it be possible to include an option to revert the rebranding also an option to replace verified organization and verified people like joe Biden with the original blue check mark and completely hide the paid for checkmarks would be nice too 

Have a great rest of your day

**Comment by neoighodaro** [comment] 2023-09-17 05:26
Hey, legitimate question, why is this something to invest time in? I see no value in it in relation to the effort. What’s the value you perceive with the change?

**Comment by GainingAccess** [comment] 2023-09-17 14:33
Because people don’t like the rebrand. We want to use Twitter, not whatever is “X.”

**Comment by neoighodaro** [comment] 2023-09-17 15:02
Got it! No offense intended, it’ll be interesting if time is invested in this as opposed to more pressing features / bugs but I do understand.

**Comment by LPFchan** [comment] 2023-09-29 01:03
Duplicate of #177 and #181
I want it too though :p

**Comment by gingerbeardman** [comment] 2024-06-16 17:28
App version 9.6.6 was the last version with the bird. 

It would be great to get the option of installing that version of it wasn't possible to rebrand the current X app.

**Closed** 2024-09-06 22:01 UTC

**Comment by gingerbeardman** [comment] 2024-09-06 23:37
hi, what was the resolution of this issue? thanks
